spring:
  application:
    name: push-based-tasklist


  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true

camunda:
  client:
    mode: saas
    auth:
      client-id: xxx
      client-secret: xxx
    cluster-id: xxx
    region: bru-2
    zeebe:
      prefer-rest-over-grpc: false
      rest-address: https://bru-2.zeebe.camunda.io/xxx